trigger:
- main

pool:
  name: my-agent-pool  # Use the self-hosted agent pool

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'  # Directly specify the Python version
  displayName: 'Use Python 3.11'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'
